[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# this part handles the initial sorting when the game is booted and the blind is selected
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "function Game:start_run(args)"
position = "after"
payload = '''
nullifySort()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "self.config.sort = config.sort or 'desc'"
position = "at"
payload = '''
self.config.sort = config.sort or default_sort
'''
match_indent = true

# SUIT SORTING
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.hand:sort('suit desc')"
position = "at"
payload = '''
sort_ascending = asc_bool
if sort_ascending_suit == nil then
	G.hand:sort('suit '..opp_order)
	sort_ascending_suit = asc_bool
elseif not sort_ascending_suit then
	G.hand:sort('suit desc')
	sort_ascending_suit = true
else
	G.hand:sort('suit asc')
	sort_ascending_suit = false
end
'''
match_indent = true

# RANK SORTING
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.hand:sort('desc')"
position = "at"
payload = '''
sort_ascending_suit = asc_bool
if sort_ascending == nil then
	G.hand:sort(opp_order)
	sort_ascending = asc_bool
elseif not sort_ascending then
	G.hand:sort('desc')
	sort_ascending = true
else
	G.hand:sort('asc')
	sort_ascending = false
end
'''
match_indent = true