[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Adding the "Auto" button
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
{n=G.UIT.C, config={align = "cm", minh = 0.7, minw = 0.9, padding = 0.1, r = 0.1, hover = true, colour =G.C.ORANGE, button = "sort_hand_value", shadow = true}, nodes={
  {n=G.UIT.T, config={text = localize('k_rank'), scale = text_scale*0.7, colour = G.C.UI.TEXT_LIGHT}}
}},
'''
position = "before"
payload = '''
{n=G.UIT.C, config={align = "cm", minh = 0.7, minw = 0.9, padding = 0.1, r = 0.1, hover = true, colour = G.C.CHIPS, button = "sort_hand_null", shadow = true}, nodes={
  {n=G.UIT.T, config={text = "Auto", scale = text_scale*0.7, colour = G.C.UI.TEXT_LIGHT}}
}},
'''
match_indent = true

# Callback func for the "Auto" button
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.FUNCS.sort_hand_suit = function(e)"
position = "before"
payload = '''
G.FUNCS.sort_hand_null = function(e)
	sort_button_bool = not sort_button_bool
	if sort_button_bool then
		G.hand:sort(default_sort)
	end
end
'''
match_indent = true